name: CI-linux

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    env:
      TLRENDER_MMAP: ON
      TLRENDER_COVERAGE: OFF
      TLRENDER_PYTHON: OFF
      TLRENDER_OCIO: ON
      TLRENDER_AUDIO: ON
      TLRENDER_FREETYPE: ON
      TLRENDER_JPEG: ON
      TLRENDER_TIFF: ON
      TLRENDER_PNG: ON
      TLRENDER_EXR: ON
      TLRENDER_FFMPEG: ON
      TLRENDER_GL: ON
      TLRENDER_QT5: OFF
      TLRENDER_PROGRAMS: OFF
      TLRENDER_EXAMPLES: OFF
      TLRENDER_TESTS: OFF

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Update
      run: sudo apt-get update

    - name: Install OpenGL dev
      if: env.TLRENDER_GL == 'ON'
      run: sudo apt-get install -y xorg-dev libglu1-mesa-dev mesa-common-dev

    - name: Install X11 dev
      run: sudo apt-get install -y libx11-dev libxcursor-dev libxinerama-dev
      
    - name: Install ALSA dev
      run: sudo apt-get install -y libasound2-dev

    - name: Install PulseAudio dev
      run: sudo apt-get install -y libpulse-dev
      
    - name: Install Pango dev
      run: sudo apt-get install -y libpango1.0-dev
      
    - name: Install Wayland
      run: sudo apt-get install -y libwayland-dev wayland-protocols libdbus-1-dev libxkbcommon-dev libegl-dev libgtk-3-dev
      
    - name: Install Codecs
      run: sudo apt-get install -y libvpx-dev
      
    - name: Install ninja-build
      run: sudo apt-get install -y ninja-build

    - name: Setup environment
      run: >
        echo "$PWD/BUILD-Linux-64/Release/install/bin" >> $GITHUB_PATH &&
        echo "CPU_CORES=$(awk '/^processor/ {++n} END {print n+1}' /proc/cpuinfo)" >> $GITHUB_ENV &&
        echo "LD_LIBRARY_PATH=$PWD/BUILD-Linux-64/Release/install/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Build mrv2
      run: >
        ./runme.sh -v -j $CPU_CORES
